# Generated by Django 3.2.19 on 2023-08-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_holding', '0002_alter_offerinformation_card_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerinformation',
            name='username',
            field=models.CharField(default=0.0005, max_length=100),
            preserve_default=False,
        ),
    ]
