# Generated by Django 3.2.19 on 2023-08-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_holding', '0003_offerinformation_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerinformation',
            name='card_number',
            field=models.BinaryField(max_length=512),
        ),
    ]
