# Generated by Django 3.2.19 on 2023-06-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PriceAlert', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pricealert',
            table='PriceAlert_pricealert',
        ),
    ]
