# Generated by Django 3.2.19 on 2023-06-22 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PriceAlert', '0002_alter_pricealert_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceAlert',
        ),
    ]
