# Generated by Django 3.2.19 on 2023-06-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20230612_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmation_hotel_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
