# Generated by Django 3.2.19 on 2023-06-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_order_confirmation_hotel_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='provider_hotel_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
