# Generated by Django 3.2.19 on 2023-06-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_order_provider_hotel_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='confirmation_hotel_number',
            new_name='Booking_ID',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='provider_hotel_number',
            new_name='Origin_System_Code',
        ),
        migrations.AddField(
            model_name='order',
            name='Provider_Confirmation_ID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Reference_ID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
